name: CI Mentoria
on: 
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000

    steps:
      - name: Clone do Projeto
        uses: actions/chechout@v4
      - name: Instalando as dependencias do projeto
        run: npm install
      - name: Iniciando o servidor de mocks
        run: npm run mock-server &
      - name: Iniciando o servidor da aplicacao
        run: npm run server &
      - name: Executando os testes do projeto
        run: npm run test
